const citiesF1 = [
  { id: 1, name: "Тюмень", averageYandex: 81442, averageVK: 33641 },
  { id: 3, name: "Можга", averageYandex: 0, averageVK: 0 },
  { id: 4, name: "Ишим", averageYandex: 14945, averageVK: 11124 },
  { id: 5, name: "Когалым", averageYandex: 0, averageVK: 0 },
  { id: 6, name: "Курган", averageYandex: 19570, averageVK: 1170 },
  { id: 7, name: "Лангепас", averageYandex: 0, averageVK: 0 },
  { id: 8, name: "Лянтор", averageYandex: 0, averageVK: 0 },
  { id: 9, name: "Набережные Челны", averageYandex: 0, averageVK: 0 },
  { id: 10, name: "Нижний Тагил", averageYandex: 6461, averageVK: 9841 },
  { id: 11, name: "Новый Уренгой", averageYandex: 14408, averageVK: 3114 },
  { id: 12, name: "Ноябрьск", averageYandex: 0, averageVK: 0 },
  { id: 13, name: "Губкинский", averageYandex: 0, averageVK: 0 },
  { id: 14, name: "Муравленко", averageYandex: 0, averageVK: 0 },
  { id: 15, name: "Тарко-Сале", averageYandex: 0, averageVK: 0 },
  { id: 16, name: "Сарапул", averageYandex: 0, averageVK: 0 },
  { id: 17, name: "Оренбург", averageYandex: 0, averageVK: 0 },
  { id: 18, name: "Ростов-на-Дону", averageYandex: 13919, averageVK: 6757 },
  { id: 19, name: "Самара", averageYandex: 6639, averageVK: 1126 },
  { id: 20, name: "Санкт-Петербург", averageYandex: 57985, averageVK: 21524 },
  { id: 21, name: "Саранск", averageYandex: 16619, averageVK: 6743 },
  { id: 22, name: "Севастополь", averageYandex: 44315, averageVK: 1170 },
  { id: 23, name: "Сургут", averageYandex: 40192, averageVK: 24283 },
  { id: 24, name: "Тобольск", averageYandex: 13753, averageVK: 10418 },
  { id: 25, name: "Челябинск", averageYandex: 11596, averageVK: 0 },
  { id: 26, name: "Ялуторовск", averageYandex: 23697, averageVK: 6839 },
  { id: 27, name: "Горно-Алтайск", averageYandex: 23697, averageVK: 6839 },
  { id: 28, name: "Новосибирск", averageYandex: 23697, averageVK: 6839 },
  { id: 29, name: "Бердск", averageYandex: 23697, averageVK: 6839 },
];

const citiesF2 = [
  { id: 1, name: "Анапа" },
  { id: 3, name: "Благовещенск" },
  { id: 4, name: "Брянск" },
  { id: 5, name: "Владивосток" },
  { id: 6, name: "Вологда" },
  { id: 7, name: "Волхов" },
  { id: 8, name: "Воронеж" },
  { id: 9, name: "Воскресенск" },
  { id: 10, name: "Выкса" },
  { id: 11, name: "Геленджик" },
  { id: 12, name: "Горячий Ключ" },
  { id: 13, name: "Дмитров" },
  { id: 14, name: "Златоуст" },
  { id: 15, name: "Ижевск" },
  { id: 16, name: "Йошкар-Ола" },
  { id: 17, name: "Казань" },
  { id: 18, name: "Калуга" },
  { id: 19, name: "Кемерово" },
  { id: 20, name: "Кириши" },
  { id: 21, name: "Киров" },
  { id: 22, name: "Краснодар" },
  { id: 23, name: "Курск" },
  { id: 24, name: "Майкоп" },
  { id: 25, name: "Миасс" },
  { id: 26, name: "Муром" },
  { id: 27, name: "Надым" },
  { id: 28, name: "Нижневартовск" },
  { id: 29, name: "Нижний Новгород" },
  { id: 30, name: "Новороссийск" },
  { id: 31, name: "Омск" },
  { id: 32, name: "Пермь 2" },
  { id: 33, name: "Свободный" },
  { id: 34, name: "Смоленск" },
  { id: 35, name: "Стерлитамак" },
  { id: 36, name: "Тамбов" },
  { id: 37, name: "Темрюк" },
  { id: 38, name: "Тольятти" },
  { id: 39, name: "Тула" },
  { id: 40, name: "Ульяновск" },
  { id: 41, name: "Уфа" },
  { id: 42, name: "Феодосия" },
  { id: 43, name: "Хабаровск" },
  { id: 44, name: "Ханты-Мансийск" },
  { id: 45, name: "Чебаркуль" },
  { id: 46, name: "Череповец" },
  { id: 47, name: "Шексна" },
  { id: 48, name: "Элиста" },
  { id: 49, name: "Энгельс" },
  { id: 50, name: "Южноуральск" },
  { id: 51, name: "Югра" },
  { id: 52, name: "Якутск" },
  { id: 53, name: "Ялта" },
  { id: 54, name: "Ярославль" },
  { id: 55, name: "Богородицк" },
  { id: 56, name: "Белгород" },
  { id: 57, name: "Саратов" },
  { id: 58, name: "Горячий ключ" },
  { id: 59, name: "Юрга" },
];

export { citiesF1, citiesF2 };
